<?php

function engelsystem_email_to_user($recipient_user, $title, $message, $not_if_its_me = false) {
  global $user;
  
  if ($not_if_its_me && $user['UID'] == $recipient_user['UID'])
    return true;
  
  gettext_locale($recipient_user['Sprache']);
  
  $message = sprintf(_("Hi %s,"), $recipient_user['Nick']) . "\n\n" . _("here is a message for you from the engelsystem:") . "\n\n" . $message . "\n\n" . _("This email is autogenerated and has not to be signed. You got this email because you are registered in the engelsystem.");
  
  gettext_locale();
  return engelsystem_email($recipient_user['email'], $title, $message);
}

function engelsystem_email($recipient, $subject, $body) {
  global $mailConfig;

  $transport = Swift_SmtpTransport::newInstance($mailConfig['smtp_host'], $mailConfig['smtp_port'])
    ->setUsername($mailConfig['smtp_user'])
    ->setPassword($mailConfig['smtp_password']);
  $mailer = Swift_Mailer::newInstance($transport);
  
  $message = Swift_Message::newInstance($subject)
    ->setFrom(array($mailConfig['sender_address'] => $mailConfig['sender_name']))
    ->setTo(array($recipient))
    ->setBody($body);

  return $mailer->send($message);
}

?>
